name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy
          targets: riscv64imac-unknown-none-elf
      - name: Check code format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          riscv32imac-unknown-none-elf,
          riscv64imac-unknown-none-elf,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: llvm-tools-preview
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --all-features --target ${{ matrix.target }}
      - name: Build docs
        run: cargo doc --target ${{ matrix.target }}

  qemu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: riscv64imac-unknown-none-elf
      - run: sudo apt-get update && sudo apt-get install -y qemu-system-misc
      - name: Build example
        run: cargo build --target riscv64imac-unknown-none-elf
        working-directory: example
      - name: Run in QEMU
        run: timeout 30 qemu-system-riscv64 -machine virt -nographic -bios default -kernel target/riscv64imac-unknown-none-elf/debug/opensbi-rt-example > qemu.log 2>&1; true
        working-directory: example
      - name: Check output
        run: |
          grep -q "Hello, OpenSBI!" qemu.log
          grep -q "hartid=0, dtb=" qemu.log
          grep -q "spec_version = SpecVersion" qemu.log
        working-directory: example
