name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy
          targets: riscv64imac-unknown-none-elf
      - name: Check code format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          riscv32imac-unknown-none-elf,
          riscv64imac-unknown-none-elf,
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --all-features --target ${{ matrix.target }}
      - name: Build docs
        run: cargo doc --target ${{ matrix.target }}
